"""
Testing tools.
~~~~~~~~~~~~~~
"""

user_data = dict(
    email="test@regular.com",
    name="Regular User",
    username="",
    password="RegularUser123!",
    organization=1,
    short_name="RU",
    first_name="Regular",
    last_name="User",
)

admin_data = dict(
    email="test@admin.com",
    name="Admin User",
    username="admin_user",
    password="AdminUser123!",
    organization=1,
    short_name="AU",
    first_name="Admin",
    last_name="User",
)

super_user_data = dict(
    email="test@sudo.com",
    name="Super User",
    username="super_user",
    password="SuperUser01!",
    organization=1,
    short_name="SU",
    first_name="Super",
    last_name="User",
)

emails = [
    "053sph@gmail.com",
    "1127.kimberly@gmail.com",
    "1539601486@qq.com",
    "1990G8REngineer@gmail.com",
    "1constmgr@gmail.com",
    "1jlanger@comcast.net",
    "1kr.davis@gmail.com",
    "1marini@bellsouth.net",
    "1rajiv@gmail.com",
    "1seh@earthlink.net",
    "2001g8tor@gmail.com",
    "2001g8tor@gmail.com",
    "2001soni@gmail.com",
    "2001ufgator@comcast.net",
    "2001ufgator@comcast.net",
    "2011AZChris@Gmail.com",
    "2014@visionengineering.us",
    "22iriswalden@gmail.com",
    "24mlove24@gmail.com",
    "281livengood@comcast.net",
    "2brian.broussard@gmail.com",
    "2chris.clark@gmail.com",
    "2chris.clark@gmail.com",
    "2dennykort@gmail.com",
    "2divefor@embarqmail.com",
    "2dsherrill@gmail.com",
    "2dsherrill@gmail.com",
    "2jssogge@q.com",
    "3.0x10e8@gmail.com",
    "3000mendez@gmail.com",
    "3720@cfl.rr.com",
    "3dnielsen@gmail.com",
    "3krids3653@gmail.com",
    "3ncfishers@gmail.com",
    "3pinestreefarm@tampabay.rr.com",
    "3rdtry137@comcast.net",
    "450KNOBBY@ATT.NET",
    "4av@bellsouth.net",
    "4millers@tampabay.rr.com",
    "4panders4@gmail.com",
    "5brown@fit.edu",
    "5gators@gmail.com",
    "5Houstons@tampabay.rr.com",
    "5remichs@cox.net",
    "5trimbles@suddenlink.net",
    "64panhead@comcast.net",
    "64panhead@comcast.net",
    "689@comcast.net",
]
